# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.delete_all
Business.delete_all

u1 = User.create!(email: 'guest', first_name: 'guest', last_name: 'guest', zipcode: '00000', password: 'password')
u2 = User.create!(email: 'fan@email.com', first_name: 'Fan', last_name: 'Fan', zipcode: '000000', password: 'password')
u3 = User.create!(email: 'david@email.com', first_name: 'David', last_name: 'Lai', zipcode: '00000', password: 'password')
u4 = User.create!(email: 'michael@email.com', first_name: 'Michael', last_name: 'Lau', zipcode: '00000', password: 'password')
u5 = User.create!(email: 'anthony@email.com', first_name: 'Anthony', last_name: 'Chen', zipcode: '00000', password: 'password')
u6 = User.create!(email: 'linda@email.com', first_name: 'Linda', last_name: 'Xiao', zipcode: '00000', password: 'password')
u7 = User.create!(email: 'fuller@email.com', first_name: 'Fuller', last_name: 'Le', zipcode: '00000', password: 'password')
u8 = User.create!(email: 'dennis@email.com', first_name: 'Dennis', last_name: 'Yu', zipcode: '00000', password: 'password')

b1 = Business.create!(business_name: "Egghead", address: "949 Ruff Dr San Jose", city: "San Jose", state: "CA", zip: "95110", phone_number: "(510) 552-0304", website_url: "eggheadcafe.net", owner_id: u3.id)
b2 = Business.create!(business_name: "Mochill Mochi Donut", address: "675 Saratoga Ave Ste 108", city: "San Jose", state: "CA", zip: "95129", phone_number: "", website_url: "mochillsf.com", owner_id: u3.id)
b3 = Business.create!(business_name: "Urban Ritual", address: "100 N Almaden Ave", city: "San Jose", state: "CA", zip: "95110", phone_number: "(408) 564-0925", website_url: "urbanritualcafe.com", owner_id: u3.id)
b4 = Business.create!(business_name: "Sno-Crave Tea House", address: "43773 Boscell Rd", city: "Fremont", state: "CA", zip: "94538", phone_number: "(510) 651-8888", website_url: "snocrave.com", owner_id: u3.id)
b5 = Business.create!(business_name: "yakiniQ SJ", address: "1783 W San Carlos St", city: "San Jose", state: "CA", zip: "95128", phone_number: "(408) 293-2668", website_url: "yesmeats.menu11.com", owner_id: u3.id)
b6 = Business.create!(business_name: "Ramen Nagi", address: "541 Bryant St", city: "Palo Alto", state: "CA", zip: "94301", website_url: "ramennagiusa.com", owner_id: u3.id)
b7 = Business.create!(business_name: "Shuei-Do Manju Shop", address: "217 Jackson St", city: "San Jose", state: "CA", zip: "95112", phone_number: "(408) 294-4148", website_url: "japantownsanjose.org/shueidomanjushop.html", owner_id: u3.id)
b8 = Business.create!(business_name: "Uncle Tetsu", address: "2855 Stevens Creek Blvd", city: "Santa Clara", state: "CA", zip: "95050", phone_number: "(408) 663-6781", website_url: "uncletetsu-us.com", owner_id: u3.id)
b9 = Business.create!(business_name: "Izumi Matcha", address: "3005 Silver Creek Rd Ste", city: "San Jose", state: "CA", zip: "95121", phone_number: "", website_url: "izumimatcha.com", owner_id: u3.id)
b10 = Business.create!(business_name: "Dr.ink", address: "77 N Almaden Ave Ste 70", city: "San Jose", state: "CA", zip: "95510", phone_number: "(408) 352-5169", website_url: "dr-ink.space", owner_id: u3.id)
b11 = Business.create!(business_name: "Philz Coffee", address: "118 Paseo De San Antonio Walk", city: "San Jose", state: "CA", zip: "95112", phone_number: "(408) 971-4212", website_url: "philzcoffee.com", owner_id: u3.id)
b12 = Business.create!(business_name: "Daeho Kalbi Jjim & Beef Soup", address: "217 W Calaveras Blvd", city: "Milpitas", state: "CA", zip: "95035", phone_number: "(408) 770-3778", website_url: "", owner_id: u3.id)
b13 = Business.create!(business_name: "Claw Shack", address: "1696 Berryessa Rd", city: "San Jose", state: "CA", zip: "95133", phone_number: "(408) 649-6741", website_url: "clawshack.com", owner_id: u3.id)
b14 = Business.create!(business_name: "TP Tea", address: "10787 S Blaney Ave", city: "Cupertino", state: "CA", zip: "95014", phone_number: "(408) 982-3902", website_url: "", owner_id: u3.id)
b15 = Business.create!(business_name: "CHICK N' BROS", address: "3242 Stevens Creek Blvd", city: "San Jose", state: "CA", zip: "95117", phone_number: "(408) 789-8816", website_url: "chicknbros.com", owner_id: u3.id)


b1.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/egghead1.jpeg")), filename: "egghead1.jpeg")
b1.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/egghead2.jpeg")), filename: "egghead2.jpeg")
b1.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/egghead3.jpeg")), filename: "egghead3.jpeg")
b1.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/egghead4.jpeg")), filename: "egghead4.jpeg")
b1.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/egghead5.jpeg")), filename: "egghead5.jpeg")

b2.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/mochill1.jpeg")), filename: "mochill1.jpeg")
b2.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/mochill2.jpeg")), filename: "mochill2.jpeg")
b2.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/mochill3.jpeg")), filename: "mochill3.jpeg")

b3.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/urbanritual1.jpeg")), filename: "urbanritual1.jpeg")
b3.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/urbanritual2.jpeg")), filename: "urbanritual2.jpeg")
b3.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/urbanritual3.jpeg")), filename: "urbanritual3.jpeg")

b4.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/snocrave1.jpeg")), filename: "snocrave1.jpeg")
b4.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/snocrave2.jpeg")), filename: "snocrave2.jpeg")

b5.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/yakiniq1.jpeg")), filename: "yakiniq1.jpeg")
b5.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/yakiniq2.jpeg")), filename: "yakiniq2.jpeg")
b5.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/yakiniq3.jpeg")), filename: "yakiniq3.jpeg")

b6.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/ramennagi1.jpeg")), filename: "ramennagi1.jpeg")
b6.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/ramennagi2.jpeg")), filename: "ramennagi2.jpeg")
b6.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/ramennagi3.jpeg")), filename: "ramennagi3.jpeg")

b7.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/mochi1.jpeg")), filename: "mochi1.jpeg")
b7.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/mochi2.jpeg")), filename: "mochi2.jpeg")
b7.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/mochi3.jpeg")), filename: "mochi3.jpeg")
b7.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/mochi4.jpeg")), filename: "mochi4.jpeg") 

b8.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/uncletetsu1.jpeg")), filename: "uncletetsu1.jpeg") 
b8.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/uncletetsu2.jpeg")), filename: "uncletetsu2.jpeg") 
b8.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/uncletetsu3.jpeg")), filename: "uncletetsu3.jpeg") 

b9.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/izumi1.jpeg")), filename: "izumi1.jpeg") 
b9.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/izumi2.jpeg")), filename: "izumi2.jpeg") 
b9.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/izumi3.jpeg")), filename: "izumi3.jpeg") 

b10.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/drink1.jpeg")), filename: "drink1.jpeg") 
b10.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/drink2.jpeg")), filename: "drink2.jpeg") 
b10.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/drink3.jpeg")), filename: "drink3.jpeg") 

b11.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/philz1.jpeg")), filename: "philz1.jpeg") 
b11.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/philz2.jpeg")), filename: "philz2.jpeg") 
b11.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/philz3.jpeg")), filename: "philz3.jpeg")

b12.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/daeho1.jpeg")), filename: "daeho1.jpeg")
b12.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/daeho2.jpeg")), filename: "daeho2.jpeg")
b12.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/daeho3.jpeg")), filename: "daeho3.jpeg")

b13.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/clawshack1.jpeg")), filename: "clawshack1.jpeg")
b13.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/clawshack2.jpeg")), filename: "clawshack2.jpeg")
b13.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/clawshack3.jpeg")), filename: "clawshack3.jpeg")

b14.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/tptea1.jpeg")), filename: "tptea1.jpeg")
b14.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/tptea2.jpeg")), filename: "tptea2.jpeg")
b14.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/tptea3.jpeg")), filename: "tptea3.jpeg")

b15.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/chicknbros1.jpeg")), filename: "chicknbros1.jpeg")
b15.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/chicknbros2.jpeg")), filename: "chicknbros2.jpeg")
b15.photos.attach(io: File.open(File.join(Rails.root, "/app/assets/images/chicknbros3.jpeg")), filename: "chicknbros3.jpeg")

t1 = Tag.create!(tag: "Drinks")
t2 = Tag.create!(tag: "Dinner")
t3 = Tag.create!(tag: "Dessert")
t4 = Tag.create!(tag: "Brunch")
t5 = Tag.create!(tag: "Sandwiches")
t6 = Tag.create!(tag: "Boba")
t7 = Tag.create!(tag: "Coffee")
t8 = Tag.create!(tag: "Korean")
t9 = Tag.create!(tag: "Seafood")

bt1 = BusinessTag.create!(business_id: b1.id, tag_id: t4.id)
bt2 = BusinessTag.create!(business_id: b1.id, tag_id: t5.id)
bt3 = BusinessTag.create!(business_id: b2.id, tag_id: t3.id)
bt4 = BusinessTag.create!(business_id: b3.id, tag_id: t1.id)
bt5 = BusinessTag.create!(business_id: b3.id, tag_id: t6.id)
bt6 = BusinessTag.create!(business_id: b4.id, tag_id: t3.id)
bt7 = BusinessTag.create!(business_id: b5.id, tag_id: t2.id)
bt8 = BusinessTag.create!(business_id: b6.id, tag_id: t2.id)
bt9 = BusinessTag.create!(business_id: b7.id, tag_id: t3.id)
bt10 = BusinessTag.create!(business_id: b8.id, tag_id: t3.id)
bt11 = BusinessTag.create!(business_id: b9.id, tag_id: t3.id)
bt12 = BusinessTag.create!(business_id: b10.id, tag_id: t6.id)
bt13 = BusinessTag.create!(business_id: b10.id, tag_id: t3.id)
bt14 = BusinessTag.create!(business_id: b10.id, tag_id: t1.id)
bt15 = BusinessTag.create!(business_id: b11.id, tag_id: t7.id)
bt16 = BusinessTag.create!(business_id: b11.id, tag_id: t1.id)
bt17 = BusinessTag.create!(business_id: b12.id, tag_id: t2.id)
bt18 = BusinessTag.create!(business_id: b12.id, tag_id: t8.id)
bt19 = BusinessTag.create!(business_id: b5.id, tag_id: t8.id)
bt20 = BusinessTag.create!(business_id: b13.id, tag_id: t2.id)
bt21 = BusinessTag.create!(business_id: b13.id, tag_id: t9.id)
bt22 = BusinessTag.create!(business_id: b14.id, tag_id: t1.id)
bt23 = BusinessTag.create!(business_id: b14.id, tag_id: t3.id)
bt24 = BusinessTag.create!(business_id: b14.id, tag_id: t6.id)
bt25 = BusinessTag.create!(business_id: b15.id, tag_id: t5.id)

r1 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b1.id)
r2 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b1.id)
r3 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b1.id)
r4 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b1.id)
r5 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b1.id)
r6 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b1.id)
r7 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b1.id)

r8 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b2.id)
r9 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b2.id)
r10 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b2.id)
r11 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b2.id)
r12 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b2.id)
r13 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b2.id)
r14 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b2.id)

r15 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b3.id)
r16 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b3.id)
r17 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b3.id)
r18 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b3.id)
r19 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b3.id)
r20 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b3.id)
r21 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b3.id)

r22 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b4.id)
r23 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b4.id)
r24 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b4.id)
r25 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b4.id)
r26 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b4.id)
r27 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b4.id)
r28 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b4.id)

r29 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b5.id)
r30 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b5.id)
r31 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b5.id)
r32 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b5.id)
r33 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b5.id)
r34 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b5.id)
r35 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b5.id)

r36 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b6.id)
r37 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b6.id)
r38 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b6.id)
r39 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b6.id)
r40 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b6.id)
r41 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b6.id)
r42 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b6.id)

r43 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b7.id)
r44 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b7.id)
r45 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b7.id)
r46 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b7.id)
r47 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b7.id)
r48 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b7.id)
r49 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b7.id)

r50 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b8.id)
r51 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b8.id)
r52 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b8.id)
r53 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b8.id)
r54 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b8.id)
r55 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b8.id)
r56 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b8.id)

r57 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b9.id)
r58 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b9.id)
r59 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b9.id)
r60 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b9.id)
r61 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b9.id)
r62 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b9.id)
r63 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b9.id)

r64 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b10.id)
r65 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b10.id)
r66 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b10.id)
r67 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b10.id)
r68 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b10.id)
r69 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b10.id)
r70 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b10.id)

r71 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b11.id)
r72 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b11.id)
r73 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b11.id)
r74 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b11.id)
r75 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b11.id)
r77 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b11.id)
r78 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b11.id)

r79 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b12.id)
r80 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b12.id)
r81 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b12.id)
r82 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b12.id)
r83 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b12.id)
r84 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b12.id)
r85 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b12.id)

r86 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b13.id)
r87 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b13.id)
r88 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b13.id)
r89 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b13.id)
r90 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b13.id)
r91 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b13.id)
r92 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b13.id)

r93 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b14.id)
r94 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b14.id)
r95 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b14.id)
r96 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b14.id)
r97 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b14.id)
r98 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b14.id)
r99 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b14.id)

r100 = Review.create!(body: "This place has really amazing food. I come here every weekend.", rating: 4, author_id: u2.id, business_id: b15.id)
r101 = Review.create!(body: "This is my favorite spot. I highly recommend this place and I try to come here as often as I can. If I could come here everyday I would!", rating: 5, author_id: u3.id, business_id: b15.id)
r102 = Review.create!(body: "My favorite thing about this place is the ambience. The food is good too, but I really enjoy the atmosphere this place offers.", rating: 3, author_id: u4.id, business_id: b15.id)
r103 = Review.create!(body: "The best thing about this place is the water.", rating: 2, author_id: u5.id, business_id: b15.id)
r104 = Review.create!(body: "I can't wait to visit this place on the weekends and get my favorite drink. I look forward to the weekends just so I can get a drink at this place. I highly recommend this place. I've recommended this place to all of my friends and they all love it!", rating: 4, author_id: u6.id, business_id: b15.id)
r105 = Review.create!(body: "I'm not a big fan of the way they make the food here. A lot of improvements could be made.", rating: 2, author_id: u7.id, business_id: b15.id)
r106 = Review.create!(body: "Overall really enjoy the food here. They make a great combination and variety of things so many people will be able to find something they like. I sometimes come here with my dog as well and read a book outside. Really nice on a Sunday afternoon.", rating: 5, author_id: u8.id, business_id: b15.id)